global:
  scrape_interval: 15s
  external_labels:
    deployment: 'production'
rule_files:
  - /prometheus-data/recording.rules.yml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'clj-documint-prod'
    dns_sd_configs:
      - names:
        - clj-documint.fusion
        refresh_interval: 15s
        type: A
        port: 80
  - job_name: 'fusion-index-prod'
    dns_sd_configs:
      - names:
          - fusion-index.fusion
        refresh_interval: 15s
        type: A
        port: 80
