global:
  external_labels:
    deployment: 'testing'
rule_files:
  - /prometheus-data/recording.rules.yml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'HostsMetrics'
    dns_sd_configs:
      - names:
          - node-exporter
        refresh_interval: 15s
        type: A
        port: 9100
  - job_name: 'Drone'
    bearer_token_file: '/prometheus-data/drone-token'
    dns_sd_configs:
      - names:
          - drone-server.drone7
        refresh_interval: 15s
        type: A
        port: 000
  - job_name: 'clj-documint-uat'
    dns_sd_configs:
      - names:
          - clj-documint.fusion
        refresh_interval: 15s
        type: A
        port: 80
