groups:
  - name: clj-documint
    rules:
      - record: job_statusclass:http_requests_total:irate
        expr: sum(irate(http_requests_total[15m])) BY (job, statusClass)
      - record: job:http_request_latency_seconds:50p
        expr: histogram_quantile(0.5, sum(irate(http_request_latency_seconds_bucket[15m])) BY (job, le))
      - record: job:http_request_latency_seconds:90p
        expr: histogram_quantile(0.9, sum(irate(http_request_latency_seconds_bucket[15m])) BY (job, le))
      - record: job:http_request_latency_seconds:99p
        expr: histogram_quantile(0.99, sum(irate(http_request_latency_seconds_bucket[15m])) BY (job, le))
      - record: job_action:documint_actions_seconds:50p
        expr: histogram_quantile(0.5, sum(irate(documint_actions_seconds_bucket[15m])) BY (job, action, le))
      - record: job_action:documint_actions_seconds:90p
        expr: histogram_quantile(0.9, sum(irate(documint_actions_seconds_bucket[15m])) BY (job, action, le))
      - record: job_action:documint_actions_seconds:99p
        expr: histogram_quantile(0.99, sum(irate(documint_actions_seconds_bucket[15m])) BY (job, action, le))
      - record: job_action:documint_actions_total:irate
        expr: sum(irate(documint_actions_total[15m])) BY (job, action)
