groups:
  - name: clj-documint
    rules:
      - record: job_statusclass:http_requests_total:rate
        expr: sum(rate(http_requests_total[5m])) BY (job, statusClass)
      - record: job:http_request_latency_seconds:50p
        expr: histogram_quantile(0.5, sum(rate(http_request_latency_seconds_bucket[5m])) BY (job, le))
      - record: job:http_request_latency_seconds:90p
        expr: histogram_quantile(0.9, sum(rate(http_request_latency_seconds_bucket[5m])) BY (job, le))
      - record: job:http_request_latency_seconds:99p
        expr: histogram_quantile(0.99, sum(rate(http_request_latency_seconds_bucket[5m])) BY (job, le))
      - record: job_action:documint_actions_seconds:50p
        expr: histogram_quantile(0.5, sum(rate(documint_actions_seconds_bucket[5m])) BY (job, action, le))
      - record: job_action:documint_actions_seconds:90p
        expr: histogram_quantile(0.9, sum(rate(documint_actions_seconds_bucket[5m])) BY (job, action, le))
      - record: job_action:documint_actions_seconds:99p
        expr: histogram_quantile(0.99, sum(rate(documint_actions_seconds_bucket[5m])) BY (job, action, le))
      - record: job_action:documint_actions_total:rate
        expr: sum(rate(documint_actions_total[5m])) BY (job, action)
  - name: fusion
    rules:
      - record: job_action:fusion_finapp_requests_seconds:50p
        expr: histogram_quantile(0.5, sum(rate(fusion_finapp_requests_seconds_bucket[5m])) BY (job, source, le))
      - record: job_action:fusion_finapp_requests_seconds:90p
        expr: histogram_quantile(0.9, sum(rate(fusion_finapp_requests_seconds_bucket[5m])) BY (job, source, le))
      - record: job_action:fusion_finapp_requests_seconds:99p
        expr: histogram_quantile(0.99, sum(rate(fusion_finapp_requests_seconds_bucket[5m])) BY (job, source, le))
